In [1]:
import cv2
import numpy as np

In [2]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [14]:

def blur_image(img_path):
    img = cv2.imread(img_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 6)
    d = {}
    print('Coordinates of faces')
    
    print(faces)
    print('-'*50)
    print('Area of entire image')
    print(img.shape[0] ** 2)
    print('-'*50)
    for i in range(len(faces)): 

        area = faces[i][2]**2
        
        d[i] = area
        
    print(d)
    count = 0
    maximum_area = max(d.values())
    print('sorted values dict is ')
    sorted_values = dict(sorted(d.items(), key=lambda item: item[1]))
    print(sorted_values)
    
    for k, v in sorted_values.items():
        print(type(k))
        print('*'*10)
        print(faces[k])
        if(count == len(faces)-2):
            break
            
        else: 
            img[faces[k][1]:faces[k][1]+faces[k][3], faces[k][0]:faces[k][0]+faces[k][2]] = \
            cv2.blur(img[faces[k][1]:faces[k][1]+faces[k][3], faces[k][0]:faces[k][0]+faces[k][2]], (40,40))
            count+=1

        
        
        
#     key_min_area = [key for key in d if d[key] == maximum_area]
#     print(key_min_area)
    
#     img[faces[key_min_area][0][1]:faces[key_min_area][0][1]+faces[key_min_area][0][3], faces[key_min_area][0][0]:faces[key_min_area][0][0]+faces[key_min_area][0][2]] = \
#     cv2.blur(img[faces[key_min_area][0][1]:faces[key_min_area][0][1]+faces[key_min_area][0][3], faces[key_min_area][0][0]:faces[key_min_area][0][0]+faces[key_min_area][0][2]], (40,40))
    cv2.imshow('img', img)
    cv2.waitKey(10)
        
#     for i in range(len(faces)):
#         

  
#     image[y:y+h, x:x+w] = cv2.blur(image[y:y+h, x:x+w] ,(23,23))

# for (x, y, w, h) in faces:

blur_image('image_3.jpg')

Coordinates of faces
[[115  88 106 106]
 [637 133  89  89]
 [480 112  99  99]
 [280 116  86  86]]
--------------------------------------------------
Area of entire image
264196
--------------------------------------------------
{0: 11236, 1: 7921, 2: 9801, 3: 7396}
sorted values dict is 
{3: 7396, 1: 7921, 2: 9801, 0: 11236}
<class 'int'>
**********
[280 116  86  86]
<class 'int'>
**********
[637 133  89  89]
<class 'int'>
**********
[480 112  99  99]


In [12]:
# img = cv2.imread('image_3.jpg')
# gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# faces = face_cascade.detectMultiScale(gray, 1.1, 4)
# d = {}
# print('Coordinates of faces')
    
# print(faces)
# print('-'*50)
# print('Area of entire image')
# print(img.shape[0] ** 2)
# print('-'*50)
# for i in range(len(faces)): 

#         area = faces[i][2]**2
        
#         d[i] = area
        
# print(d)
# minimum_area = max(d.values())
# key_min_area = [key for key in d if d[key] == minimum_area]
# print(key_min_area)
# img[faces[key_min_area][0][1]:faces[key_min_area][0][1]+faces[key_min_area][3],faces[key_min_area][0]:faces[key_min_area][0]+faces[key_min_area][2]] = \
# cv2.blur(img[faces[key][0][1]:faces[i][1]+faces[i][3], faces[i][0]:faces[i][0]+faces[i][2]], (40,40))

# img[faces[key_min_area][1]:faces[key_min_area][1]+faces[key_min_area][3], faces[key_min_area][0]:faces[key_min_area][0]+faces[key_min_area][2]] = cv2.blur(img[faces[key_min_area][1]:faces[key_min_area][1]+faces[key_min_area][3], faces[key_min_area][0]:faces[key_min_area][0]+faces[key_min_area][2]], (40,40))
# cv2.imshow('img', img)
# cv2.waitKey(10)

In [34]:
faces[key_min_area][0][0]

115

In [20]:
#         length = abs(np.sum(np.subtract(faces[i][0], faces[i][2])))
#         width = abs(np.sum(np.subtract(faces[i][1], faces[i][3])))

In [21]:
# length = abs(np.sum(np.subtract(faces[0][0], faces[0][2])))
# width = abs(np.sum(np.subtract(faces[0][1], faces[0][3])))
# print(length)
# print(width)